version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: jobscraper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobscraperdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data: