FROM mcr.microsoft.com/playwright/python:v1.58.0-noble

WORKDIR /app

COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

ENV WORKER_NAME=worker

CMD ["python", "-c", "import os, time; print(f'Starting {os.environ.get(\"WORKER_NAME\", \"worker\")}'); time.sleep(3600)"]
